# Generated by Django 4.2.5 on 2023-10-29 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Oquv_Markaz1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='markazimg/')),
                ('rating', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(max_length=12)),
                ('checking', models.BooleanField()),
                ('applys', models.CharField(blank=True, max_length=50)),
                ('telegram', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtobe', models.URLField(blank=True)),
                ('manzil', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viloyat1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schol.viloyat1')),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='kurs/')),
                ('davomiyligi', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('applys', models.CharField(blank=True, max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schol.category')),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schol.oquv_markaz1')),
            ],
        ),
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='ariza/')),
                ('age', models.IntegerField()),
                ('number', models.CharField(max_length=12)),
                ('ariza_chek', models.BooleanField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schol.kurs')),
            ],
        ),
    ]
