# Generated by Django 4.2.5 on 2023-10-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='viloyatlar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schol.viloyat1'),
            preserve_default=False,
        ),
    ]
